#!/bin/bash

if [ $DUNITER_INIT == "yes" ]; then
  locale_ip=`awk 'NR==7 {print $1}' /etc/hosts`
  remote_ip=`curl -s https://4.ifcfg.me/`
  if [ -n $DUNITER_SALT ] && [ -n $DUNITER_PASSWD ]; then
    identity_args="--salt $DUNITER_SALT --passwd $DUNITER_PASSWD"
  else
    identity_args=""
  fi

  echo "--- Configuring and syncing duniter daemon" >> ~/.config/duniter/duniter_default/duniter.log
  duniter init --autoconf
  duniter config --noupnp --remote4 $remote_ip --ipv4 $locale_ip $identity_args
  duniter sync $DUNITER_URL $DUNITER_PORT
else
  echo "--- Starting duniter daemon" >> ~/.config/duniter/duniter_default/duniter.log
  duniter start
  while ps -p `cat .config/duniter/duniter_default/app.pid` > /dev/null; do sleep 1; done
  echo "--- Duniter daemon terminated." >> ~/.config/duniter/duniter_default/duniter.log
fi

echo "--- Docker container terminated." >> ~/.config/duniter/duniter_default/duniter.log
